### ISSUE TITLE
Implement Edit Record

### ISSUE THREAD

**Issue by samarth-ramesh** [acmpesuecc/timetracker-server#1]
Implement the EditRecord endpoint.
It takes in a RecordId and an ``IRecord``, defined by:
```gql
enum EventType {
    Start,
    End
}

input IRecord {
    time: Int!,
    event: EventType
}
```
And returns a Boolean (True if successful, False if not).
Create a query for the editing the record in [src/dao/records.ts](https://github.com/samarth-ramesh/timetracker-server/blob/master/src/dao/records.ts) .
Then consume that query in a new ``Edit`` function in the [src/records.tsx](https://github.com/samarth-ramesh/timetracker-server/blob/master/src/records.ts) file.
Finally, consume your edit function in the [src/index.tsx](https://github.com/samarth-ramesh/timetracker-server/blob/master/src/index.ts) file (like other mutations)

**Comment by Ananya-Kini** [comment]
can i please be assigned

**Comment by euphoricair7** [comment]
Could You assign me this issue?

**Comment by samarth-ramesh** [comment]
@euphoricair7 , I assigned based on FCFS. If no updates from them in the next 30 minutes, I will assign it to you

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by samarth-ramesh** [comment]
@euphoricair7

**Comment by akshatnavlani** [comment]
can i get assigned to this ??

**Comment by samarth-ramesh** [comment]
Sure it's yours

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
